services:
  qdrant:
    image: qdrant/qdrant:v1.13.6
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  qdrant-storage:
